spring:
  application:
    name: market
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432/market}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgrespw}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  main:
    banner-mode: off

graphql:
  packages:
    - "money.tegro.market.query"
