spring:
  application:
    name: market
  main:
    banner-mode: off
  flyway:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432/market}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgrespw}
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_URL:localhost:5432/market}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgrespw}
  thymeleaf: # Thymeleaf
    cache: true
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
